# Generated by Django 5.2.5 on 2025-08-15 19:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='ProgrammingLanguage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('slug', models.SlugField(max_length=256, unique=True)),
                ('body', models.TextField()),
                ('link', models.URLField()),
                ('expertise', models.ManyToManyField(related_name='articles', to='core.expertise')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('live_url', models.URLField(blank=True, null=True)),
                ('github_url', models.URLField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/frontend/')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/frontend')),
                ('expertise', models.ManyToManyField(related_name='projects', to='core.expertise')),
                ('programming_language', models.ManyToManyField(blank=True, null=True, related_name='projects', to='core.programminglanguage')),
                ('tools', models.ManyToManyField(blank=True, null=True, related_name='projects', to='core.tool')),
            ],
        ),
    ]
